version: '3'

services:
  db:
    user: $UID
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: wefox
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

#
#   TODO: connect-redis is not saving the cookie as cache into redis container.
#         FIst solution set a local environment for Redis
#
#  cache:
#    image: redis:alpine
#    ports:
#      - '6379:6379'
#    command: ['--requirepass "secret"']